version: '3.8'
services:
  mysql:
    image: mysql:5.7.37
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./conf/mysql/scripts:/docker-entrypoint-initdb.d
      - ./conf/mysql/conf/my.cnf:/etc/mysql/my.cnf
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  control-plane:
    build: ./dockerfiles/apim
    environment:
      PROFILE_NAME: control-plane
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./conf/cp:/home/wso2carbon/wso2-config-volume
      - ./entrypoints/docker-entrypoint.sh:/home/wso2carbon/docker-entrypoint.sh
  gateway:
    build: ./dockerfiles/apim
    environment:
      PROFILE_NAME: gateway-worker
    depends_on:
      mysql:
        condition: service_healthy
      control-plane:
        condition: service_healthy
    volumnes:
      - ./conf/gateway:/home/wso2carbon/wso2-config-volume
      - ./entrypoints/docker-entrypoint.sh:/home/wso2carbon/docker-entrypoint.sh
